project_id = "zvgkzujycngerodmrflc"
[functions.notify-registration]
enabled = true
verify_jwt = false
import_map = "./functions/notify-registration/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-registration/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-registration/*.html" ]

[functions.notify-validation]
enabled = true
verify_jwt = false
import_map = "./functions/notify-validation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-validation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-validation/*.html" ]

[functions.notify-email-confirmed]
enabled = true
verify_jwt = false
import_map = "./functions/notify-email-confirmed/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-email-confirmed/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-email-confirmed/*.html" ]

[functions.admin-update-credentials]
enabled = true
verify_jwt = false
