import { create } from 'zustand';
import type { RegistrationState } from '@/types';

const initialState = {
  currentStep: 1,
  linkedinUrl: '',
  password: '',
  passwordConfirm: '',
  prenom: '',
  nom: '',
  email: '',
  telephone: '',
  photo: null as File | null,
  photoPreviewUrl: '',
  sermentMois: null as number | null,
  sermentAnnee: null as number | null,
  cabinet: '',
  cabNat: '',
  cabTier: '',
  departement: '',
  legal500: null as boolean | null,
  legal500Suivi: '',
  retrocession: '',
  bonus: '',
  hasObjectifFacturable: null as boolean | null,
  objectifFacturable: '',
  objectifFacturableReel: '',
  assocClientele: '',
  // Associé / Counsel
  isAssocieOrCounsel: false,
  statutAssoc: '' as '' | 'counsel' | 'associe',
  chiffreAffairesPortable: '',
  businessPlanFile: null as File | null,
  assocExpertiseSummary: '',
  assocProjet: '',
  assocAttentes: [] as string[],
  assocCabTypes: [] as string[],
  // Taille opérations & disponibilité
  tailleOperations: [] as string[],
  disponibilite: '',
  // Rétrocession flexibility
  conserverRetrocession: null as boolean | null,
  raisonsBaisseRetro: [] as string[],
  // RDV
  souhaitePrendreRdv: false,
  creneauPrefere: '',
  // Step 3
  activites: {} as Record<string, boolean>,
  pourcentages: {} as Record<string, number>,
  sousActivites: {} as Record<string, Record<string, number>>,
  positionnementPreteur: 50,
  clienteleFrancaise: 50,
  positionnementRestr: [] as string[],
  positionnementRestrPct: {} as Record<string, number>,
  clienteleRestr: [] as string[],
  clienteleRestrPct: {} as Record<string, number>,
  restrFinancier: 0,
  // Droit Social
  socialConseil: 50,
  socialRelationType: '' as '' | 'individuelles' | 'collectives' | 'les_deux',
  socialIndividuel: 50,
  socialEmployeur: 50,
  socialPosCabinet: { standalone: 10, corporate: 10, restructuring: 10 } as Record<string, number>,
  socialClientele: [] as string[],
  socialExpertises: [] as string[],
  // M&A / PE / VC
  maPeFonds: 50,
  maSanteVendeur: 50,
  maVcFonds: 50,
  maIndusSecteurs: [] as string[],
  maIndusClientele: [] as string[],
  maSanteClientele: [] as string[],
  maVcStades: [] as string[],
  // Concurrence
  concAcquereur: 50,
  concCtxDefense: 50,
  concDomestique: 50,
  concOpsTypes: [] as string[],
  concCtxInterventions: [] as string[],
  concConsMissions: [] as string[],
  concSecteurs: [] as string[],
  concAutorites: [] as string[],
  // Fiscal
  fiscInvestisseur: 50,
  fiscCtxDefense: 50,
  fiscDomestique: 50,
  fiscTransacOps: [] as string[],
  fiscCtxDossiers: [] as string[],
  fiscConsMissions: [] as string[],
  fiscClientele: [] as string[],
  fiscComplexite: [] as string[],
  fiscSpecialisations: [] as string[],
  // Droit Public
  dpubPublique: 50,
  dpubCtxDefense: 50,
  dpubDomestique: 50,
  dpubContratsInterventions: [] as string[],
  dpubCtxInterventions: [] as string[],
  dpubConsDomaines: [] as string[],
  dpubClientele: [] as string[],
  dpubDimensionProjets: [] as string[],
  dpubSecteurs: [] as string[],
  // Arbitration
  arbInstitutions: [] as string[],
  arbSecteurs: [] as string[],
  arbPositionnements: [] as string[],
  arbDomestique: 30,
  // Projects & Energy
  projSecteursEnergie: [] as string[],
  projTypesInfra: [] as string[],
  projPositionnements: [] as string[],
  projTaille: [] as string[],
  projDomestique: 40,
  // Real Estate / Immobilier — Conseil
  reBauxAM: 20,
  reShareDeal: 20,
  reAssetDealPct: 20,
  reConstructionPct: 20,
  reHasFinancement: null as boolean | null,
  reFinancementPct: 20,
  reShareDealCorporate: null as boolean | null,
  reShareDealMode: '',
  reAssetTypes: [] as string[],
  // Contentieux
  reHasContentieux: null as boolean | null,
  reContentieuxPct: 20,
  reContentieuxDomaines: [] as string[],
  // Urbanisme / Environnement
  reHasUrbanisme: null as boolean | null,
  reUrbanismeConseilPct: 50,
  reUrbanismeContentieuxPct: 50,
  anglais: '',
  typesClients: [] as string[],
  // Step 4 - Next move
  moveRemuneration: [] as string[],
  moveEvolution: [] as string[],
  moveManagement: [] as string[],
  moveExposition: [] as string[],
  moveCulture: [] as string[],
  movePriorities: [] as string[],
  qualitesAppreciees: [] as string[],
  axesAmelioration: [] as string[],
  motivation: '',
  bullets: ['', '', ''],
  cabinetsCibles: [] as string[],
  noGo: [] as string[],
  noGoCabinets: [] as string[],
  processusCours: '',
  // Step 5
  statutEcoute: '' as '' | 'actif' | 'passif' | 'inactif',
  visibilite: '' as '' | 'confidentiel' | 'semi-confidentiel',
  cvFile: null as File | null,
  isAdminMode: true,
  consentement: false,
  consentementExactitude: false,
  consentementMiseEnRelation: false,
};

export const useRegistrationStore = create<RegistrationState>((set) => ({
  ...initialState,
  setField: (key, value) => set({ [key]: value } as Partial<RegistrationState>),
  nextStep: () => set((s) => ({ currentStep: Math.min(s.currentStep + 1, 7) })),
  prevStep: () => set((s) => ({ currentStep: Math.max(s.currentStep - 1, 1) })),
  goToStep: (n) => set({ currentStep: n }),
  reset: () => set(initialState),
}));
